#!/bin/bash

echo
echo -e "\e[32m== Scope ==\e[0m"
echo
java -jar target/scopelang-1.0-jar-with-dependencies.jar env/$1
echo
echo -e "\e[32m== FASM ==\e[0m"
echo
fasm env/$1.asm _temp
echo
echo -e "\e[32m== Output ==\e[0m"
echo
chmod +x _temp
./_temp
echo -e "\e[2m\e[37mExited with:" $? "\e[0m"
rm _temp
echo